/** Declaration file generated by dts-gen */

declare module "dsn-parser" {

    class DSNParser {
        constructor(dsn: any);
    
        get(prop: any, def?: any): any;
    
        getDSN(): any;
    
        getParts(): any;
    
        parse(): any;
    
        set(prop: any, value: any): any;
    
    }

    export default DSNParser

}

