/** Declaration file generated by dts-gen */

declare module 'busboy-body-parser' {
    
    import { NextHandleFunction } from 'connect';

    export function busboyBodyParser(settings: settings): NextHandleFunction;

    interface settings{
        limit?: string,
        multi?: boolean
    }
}